=== jrahlf/3D-Non-Contact-Laser-Profilometer/xpcc/examples/linux/communication/basic/communication.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- DTD for the communication structure description -->

<!ELEMENT rca (description|builtin|typedef|struct|enum|event|component|container)*>
<!ATTLIST rca 
	version    CDATA    #REQUIRED
>

<!ELEMENT description (#PCDATA)>
<!ELEMENT include (#PCDATA)>

<!ELEMENT builtin (description?)>
<!ATTLIST builtin
	description CDATA #IMPLIED
	name CDATA #REQUIRED
	size CDATA #REQUIRED
>

<!ELEMENT typedef (description?)>
<!ATTLIST typedef
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	unit CDATA #IMPLIED
>

<!ELEMENT struct (description?,element*)>
<!ATTLIST struct
	name CDATA #REQUIRED
	extends CDATA #IMPLIED
	description CDATA #IMPLIED
	typeIdentifier CDATA #IMPLIED
>

<!ELEMENT enum (description?,element*)>
<!ATTLIST enum
	name CDATA #REQUIRED
>

<!ELEMENT element (description?)>
<!ATTLIST element
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	type CDATA #IMPLIED
	unit CDATA #IMPLIED
	description CDATA #IMPLIED
>

<!ELEMENT event (description?)>
<!ATTLIST event
	name CDATA #REQUIRED
	id CDATA #IMPLIED
	type CDATA #IMPLIED
	rate CDATA #IMPLIED
>

<!ELEMENT component (description|events|actions)*>
<!ATTLIST component
	id CDATA #IMPLIED
	name CDATA #REQUIRED
	extends CDATA #IMPLIED
>

<!ELEMENT events (publish?, subscribe?)>
<!ELEMENT subscribe (event*)>
<!ELEMENT publish (event*)>

<!ELEMENT actions (action*)>

<!ELEMENT action (description?,errorcode*)>
<!ATTLIST action
	name CDATA #REQUIRED
	id CDATA #IMPLIED
	function CDATA #IMPLIED
	parameterType CDATA #IMPLIED
	returnType CDATA #IMPLIED
>

<!ELEMENT container (description|component)*>
<!ATTLIST container
	name CDATA #REQUIRED
>

=== jrahlf/3D-Non-Contact-Laser-Profilometer/xpcc/examples/lpcxpresso/lpc11c24/communication/xml/communication.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE rca SYSTEM "communication.dtd">
<rca version="1.0">

<builtin name="int8_t" size="1" />
<builtin name="int16_t" size="2" />
<builtin name="int32_t" size="4" />
<builtin name="uint8_t" size="1" />
<builtin name="uint16_t" size="2" />
<builtin name="uint32_t" size="4" />
<builtin name="float" size="4" />
<builtin name="char" size="1" />

<typedef name="Bool" type="uint8_t">
	<description>On x86 systems the bool-type has 4 bytes and on AVRs it has 1 byte.
		This type is defined to make it possible to send bools from everywhere.</description>
</typedef>

<struct name="position">
	<description>Position of the Robot on the Playground.</description>
	
	<element name="x" type="int16_t" unit="mm" />
	<element name="y" type="int16_t" unit="mm" />
</struct>

<event name="position" type="position" id="0x02" >
	<description>
	</description>
</event>

<component name="sender" id="0x01">
	<description>
	</description>
	<actions>
	</actions>
	<events>
		<publish>
			<event name="position" />
		</publish>
		<subscribe>
		</subscribe>
	</events>
</component>

<component name="receiver" id="0x02">
	<description>
	</description>
	<actions>
		<action name="set position" id="0x01" parameterType="position" />
		<action name="get position" id="0x02" returnType="position" />
	</actions>
	<events>
		<publish>
		</publish>
		<subscribe>
			<event name="position" />
		</subscribe>
	</events>
</component>


<container name="sender">
	<component name="sender" />
</container>

<container name="receiver">
	<component name="receiver" />
</container>

</rca>
